---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  push:
    branches:
      - master
  schedule:
      - cron: "0 7 * * 0"

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: >-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build docker image
        run: ./build.sh

      - name: Push Docker image
        run: docker push jingke/sonarr_sickbeard_mp4_automator:latest
