---
name: Release
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
      - cron: "0 7 * * 0"

jobs:

  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install pytest-testinfra

      - name: Build image.
        run: docker build -t jingke/sonarr_sickbeard_mp4_automator .

      - name: Run the built image.
        run: docker run --name=sonarr -td jingke/sonarr_sickbeard_mp4_automator

      - name: Test the built image.
        run: py.test --hosts='docker://sonarr'

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image.
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jingke/sonarr_sickbeard_mp4_automator:latest